title: devkobe24.com
description: "Kobe - Developer blog"
logo_img: "/assets/img/favicon.webp"
profile_img: "/assets/img/profile.jpg"

# Social Links
email: "dev.skyachieve91@gmail.com"
github_username: devKobe24
twitter_username: twitter
instagram_username: instagram
linkedin_username: linkedin
facebook_username: facebook

# External API
giscus_repo: "devKobe24/devKobe24.github.io"
giscus_repoId: "R_kgDOLQxRgw"
giscus_category: "Q&A"
giscus_categoryId: "DIC_kwDOLQxRg84CdK27"
goatcounter_code:
google_analytics:

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-loading-lazy

exclude:
  - docs/

# 포스트(블로그 글) 설정
# (Jekyll은 _posts를 자동 컬렉션으로 인식하지만 permalink를 명시해두면 깔끔)
collections:
  # 정적 문서 컬렉션
  content:
    output: true
    permalink: /:path/
    # 예: categories: [study] 이면 /study/boolean-algebra/

defaults:
  - scope:
      path: ""
      type: "content"
    values:
      layout: "page"

# Markdown newline activator
kramdown:
  input: GFM
  hard_wrap: true
